### ISSUE TITLE
[Bug]: Not working in Zig 0.15.2  on macos

### ISSUE THREAD

**Issue by hironichu** [muhammad-fiaz/httpx.zig#3]
### Bug Description

Hello,

I am a very very begginer in Zig so i have little to go on with my issue, and i have noticed this repo hasn't been updated in a couple of months.

I wanted to try the library but im having some issues building it on macos using the latest stable version of zig

```
└─ install ZIG_FUN
   └─ compile exe ZIG_FUN Debug native 3 errors
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/core/response.zig:169:40: error: root source file struct 'json' has no member named 'stringifyAlloc'
        const serialized = try std.json.stringifyAlloc(self.allocator, value, .{});
                               ~~~~~~~~^~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.2/lib/zig/std/json.zig:1:1: note: struct declared here
//! JSON parsing and stringification conforming to RFC 8259. https://datatracker.ietf.org/doc/html/rfc8259
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    json__anon_19971: /Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/server/server.zig:129:35
    helloHandler: src/main.zig:5:20
    5 reference(s) hidden; use '-freference-trace=7' to see all references
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:330:33: error: expected 4 argument(s), found 3
        const handle = try posix.accept(self.handle, &addr, &addr_len);
                           ~~~~~^~~~~~~
/opt/homebrew/Cellar/zig/0.15.2/lib/zig/std/posix.zig:3916:5: note: function declared here
pub fn accept(
~~~~^~
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:392:34: error: expected type '@typeInfo(@typeInfo(@TypeOf(net.socket.TcpListener.accept)).@"fn".return_type.?).error_union.error_set!net.socket.TcpListener.accept__struct_19858', found '@typeInfo(@typeInfo(@TypeOf(net.socket.Socket.accept)).@"fn".return_type.?).error_union.error_set!net.socket.Socket.accept__struct_19867'
        return self.socket.accept();
               ~~~~~~~~~~~~~~~~~~^~
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:392:34: note: error union payload 'net.socket.Socket.accept__struct_19867' cannot cast into error union payload 'net.socket.TcpListener.accept__struct_19858'
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:327:33: note: struct declared here
    pub fn accept(self: *Self) !struct { socket: Socket, addr: net.Address } {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:391:33: note: struct declared here
    pub fn accept(self: *Self) !struct { socket: Socket, addr: net.Address } {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/net/socket.zig:391:33: note: function return type declared here
error: the following command failed with 3 compilation errors:
/opt/homebrew/Cellar/zig/0.15.2/bin/zig build-exe -ODebug --dep clap --dep httpx -Mroot=/Users/hiro/Local/Projects/2026/ZIG_FUN/src/main.zig -ODebug -Mclap=/Users/hiro/.cache/zig/p/clap-0.11.0-oBajB-jlAQA8x4XSScN1d48Q83iYl-LDU63htNyXbXBe/clap.zig -Mhttpx=/Users/hiro/.cache/zig/p/httpx-0.0.1-8qj2ekwFBgBi0Nu-g3zWzqEucJoY8KgV2VO8r0CQTvH5/src/httpx.zig --cache-dir .zig-cache --global-cache-dir /Users/hiro/.cache/zig --name ZIG_FUN --zig-lib-dir /opt/homebrew/Cellar/zig/0.15.2/lib/zig/ --listen=-

Build Summary: 0/3 steps succeeded; 1 failed
install transitive failure
└─ install ZIG_FUN transitive failure
   └─ compile exe ZIG_FUN Debug native 3 errors
```

After looking up the code, it seems that the two error might be because of some changes in ZIg but you said that it was working in the latest version, so I must be doing something wrong.

Here is my build.zig file  : 

```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const httpx_dep = b.dependency("httpx", .{
        .target = target,
        .optimize = optimize,
    });
    const httpx_mod = httpx_dep.module("httpx");

    const exe = b.addExecutable(.{
        .name = "ZIG_FUN",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    const clap = b.dependency("clap", .{});
    exe.root_module.addImport("clap", clap.module("clap"));
    exe.root_module.addImport("httpx", httpx_mod);

    b.installArtifact(exe);

    const run_step = b.step("run", "Run the app");

    const run_cmd = b.addRunArtifact(exe);
    run_step.dependOn(&run_cmd.step);

    run_cmd.step.dependOn(b.getInstallStep());

    if (b.args) |args| {
        run_cmd.addArgs(args);
    }
}
```

### Reproduction Steps

1. Created a sample main file containing a server example code from the repo
2. build
3. error

### Zig Version

0.15.2

### httpx.zig Version

main

### Operating System

Windows

### Logs or Screenshots

```shell

```
